set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if(DEFINED ENV{VCPKG_INSTALLED_DIR})
  set(CMAKE_FIND_ROOT_PATH "$ENV{VCPKG_INSTALLED_DIR}")
endif()

if(NOT DEFINED CMAKE_C_COMPILER AND DEFINED ENV{CC})
  set(CMAKE_C_COMPILER "$ENV{CC}")
endif()

if(NOT DEFINED CMAKE_C_COMPILER)
  message(FATAL_ERROR "Set CC to the Windows target C compiler")
endif()

if(DEFINED ENV{WINDRES})
  set(CMAKE_RC_COMPILER "$ENV{WINDRES}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
